language: php

php:
  - 7.0

sudo: false

install:
  - composer update --quiet

script:
  - php vendor/bin/codecept run unit --coverage-xml=coverage.clover
  - find src/ -type f -print0 | xargs -0 -n1 php -l

afetr_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - sid@sidroberts.co.uk
